# Configuration file for Natural Gas Trading System

# Environment Settings
environment: 'development'  # Options: development, staging, production

# Data Sources
data_sources:
  eia:
    base_url: "https://api.eia.gov/v2/"
    natural_gas:
      prices_url: "natural-gas/pri/sum/data/"
      storage_url: "natural-gas/stor/wkly/data/"
    series:
      ng_storage: 'NG.NW2_EPG0_SAX_R48_BCF.W'
      ng_production: 'NG.N9070US2.M'
      ng_consumption: 'NG.N3010US2.M'
  
  noaa:
    base_url: "https://www.ncdc.noaa.gov/cdo-web/api/v2/"
    datasets:
      daily_summaries: "GHCND"
      monthly_summaries: "GSOM"
      normal_daily: "NORMAL_DLY"
    locations:
      - 'CITY:US060013'  # Chicago
      - 'CITY:US360019'  # New York
      - 'CITY:US480015'  # Houston
    default_station: "USW00094728"  # Central Park, NY

  cme:
    symbol: 'NG'  # Natural Gas Futures
    exchange: 'NYMEX'

  yahoo_finance:
    # Alternative to CME for futures data
    natural_gas_symbol: "NG=F"
    crude_oil_symbol: "CL=F"

# Data processing settings
data_processing:
  default_indicators:
    - "MA_20"
    - "MA_50"
    - "RSI_14"
    - "MACD"
    - "Bollinger_Bands"
  
  weather_variables:
    - "TAVG"  # Average Temperature
    - "TMAX"  # Maximum Temperature
    - "TMIN"  # Minimum Temperature
    - "PRCP"  # Precipitation
    - "SNOW"  # Snowfall
    - "HTDD"  # Heating Degree Days
    - "CLDD"  # Cooling Degree Days

# Backtesting settings
backtesting:
  default_initial_capital: 1000000.0
  default_trade_fee: 0.0001
  default_slippage: 0.0001

# Strategy Parameters
strategies:
  momentum:
    lookback_periods: [5, 10, 20, 60]
    volatility_lookback: 20
  
  mean_reversion:
    lookback_periods: [5, 10, 20]
    z_score_threshold: 2.0
  
  fundamental:
    storage_deviation_weight: 0.4
    production_weight: 0.3
    weather_weight: 0.3

# Risk Management
risk:
  max_position_size_pct: 0.2  # 20% of portfolio
  max_drawdown_pct: 0.15  # 15% max drawdown
  stop_loss_pct: 0.05  # 5% stop loss

# Logging
logging:
  level: 'INFO'  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_to_file: true
  log_file: 'logs/trading_system.log'
  rotation: '1 day' 